"""empty message

Revision ID: ace84d9e2f37
Revises: a8d753232426
Create Date: 2021-08-06 18:17:10.148720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace84d9e2f37'
down_revision = 'a8d753232426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'image')
    # ### end Alembic commands ###
