"""empty message

Revision ID: a9c49d50c857
Revises: 1484de8351c5
Create Date: 2021-08-02 14:39:33.100445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9c49d50c857'
down_revision = '1484de8351c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('days', sa.Integer(), nullable=True))
    op.add_column('reservations', sa.Column('guests', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'guests')
    op.drop_column('reservations', 'days')
    # ### end Alembic commands ###
