"""empty message

Revision ID: a8d753232426
Revises: a9c49d50c857
Create Date: 2021-08-03 12:50:47.425024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8d753232426'
down_revision = 'a9c49d50c857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'name')
    # ### end Alembic commands ###
